#!/usr/bin/env python
#
# Config file for Firewall API
#

# Path to accesslist database (generated by preprocessing script)
ACCESSLIST_DATABASE = 'input/accesslists.db'

# Path to database of portnames to numbers, and vice versa
NAME_NUMBER_MAPPING = 'name-number-mappings.db'

